# Generated by Django 5.2.16 on 2026-07-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_project_secrets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('init', 'Инициализация'), ('snapshot', 'Snapshot'), ('watch', 'Наблюдение')], max_length=20, verbose_name='Тип'),
        ),
    ]
