# Generated by Django 5.2.16 on 2026-07-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0004_alter_job_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_iterations',
            field=models.IntegerField(blank=True, default=10, verbose_name='Максимум ходов агента'),
        ),
    ]
