# Generated by Django 5.2.16 on 2026-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0005_project_max_iterations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='llm_provider',
            field=models.CharField(blank=True, default='openai', max_length=60, verbose_name='Провайдер LLM'),
        ),
    ]
