# Generated by Django 5.2.16 on 2026-07-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0006_project_llm_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='log_path',
            field=models.TextField(blank=True, verbose_name='Путь к файлу лога'),
        ),
    ]
