# Generated by Django 5.2.16 on 2026-07-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0007_job_log_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='watch_interval',
            field=models.IntegerField(blank=True, default=10, verbose_name='Интервал наблюдения (мин)'),
        ),
    ]
