# Generated by Django 5.2.16 on 2026-07-16 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0008_project_watch_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_model', models.CharField(default='gpt-4o', max_length=120, verbose_name='Модель LLM')),
                ('llm_base_url', models.URLField(blank=True, max_length=500, verbose_name='Base URL LLM')),
                ('llm_api_key_encrypted', models.TextField(blank=True, editable=False)),
                ('github_token_encrypted', models.TextField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Повторных запусков'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True, validators=[django.core.validators.RegexValidator(message="Используйте строчные латинские буквы, цифры, '-' и '_'.", regex='^[a-z0-9][a-z0-9_-]*$')], verbose_name='Идентификатор'),
        ),
    ]
