# Generated by Django 5.2.16 on 2026-07-17 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0009_globalsettings_job_retry_count_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='max_iterations',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(500)], verbose_name='Максимум ходов агента'),
        ),
    ]
